### ISSUE TITLE
What title should the book have?

### ISSUE THREAD

**Issue by christianpeel** [JuliaIntro/IntroAJulia.jl#1]
**Updated**:  
Some options
* *"Piensa en Julia: Cómo Pensar como un Informático"*, is close to the English title and is what we started with
* *"Aprende a programar con Julia"*    We don't need to stay so close to "ThinkJulia"
* *"Introducción a la programación en Julia"*  

Diego has very good comments below

**Comment by diegozea** [comment]
The full title is *Think Julia : How to Think Like a Computer Scientist*. It looks like the short *Think insert-language-here* works well in English, but not so well in Latin languages. Therefore, most of the translations for other programming languages use the longest title: 
- [Cómo Pensar como un Informático (Spanish / Eiffel)](http://sourceforge.net/projects/httlcseifspa)
- [ Apprendre a programmer avec Python (French / Python)](https://inforef.be/swi/download/apprendre_python3_5.pdf)
- [Cómo Pensar como un Informático. El aprender con Python (Spanish / Python)](http://www.openbookproject.net/thinkcs/archive/python/spanish2e/index.html)
- [Aprenda a Pensar Como un Programador con Python (Spanish / Python)](https://argentinaenpython.com/quiero-aprender-python/aprenda-a-pensar-como-un-programador-con-python.pdf)  

Except for the Italians and Brazilians:
- [Pensare in Python: Come pensare da Informatico. (Italian / Python)](https://github.com/AllenDowney/ThinkPythonItalian)
- [Pense em Python: Pense como um cientista da computação (Portuguese / Python)](https://penseallen.github.io/PensePython2e/)

Something similar to the last ones in Spanish is:
- *Piensa/Pensar en Julia: Cómo Pensar como un Informático/Programador*.

*Aprenda a Pensar Como un Programador con Julia* can be also an option.

**Comment by christianpeel** [comment]
I wonder if "La Programación con Julia" is a better name; I don't think there's any reason to stick with something so close to "ThinkJulia"

**Comment by alejandromerchan** [comment]
"Aprender Julia. ¿Cómo pensar como un informático?" could be another option. I don't particularly like "El aprender...", that's really not a commonly used construct, IMO.

**Comment by christianpeel** [comment]
Pamela and a couple of other Spanish speakers think *"Introducción a la programación en Julia"*  is better than our current title.  If we go for this, I'd like to change the name of the repo (and corresponding package) to something like "IntroAJulia.jl".  

I'd like to finalize the name soon.

**Comment by alejandromerchan** [comment]
That title is also very nice.

**Comment by christianpeel** [comment]
I changed the title to "Introducción a la programación en Julia", which seemed acceptable.

I also changed the name of the package to "IntroAJulia.jl".    Unless this is somehow a problem, I plan to close the ticket.
