### ISSUE TITLE
Floor division translation to Spanish

### ISSUE THREAD

**Issue by oscarbelmon** [JuliaIntro/IntroAJulia.jl#42]
Hi everyone.
I'm reviewing Chapter 5 and have found the translation for the operator "floor division" as "división entera de tipo piso". I would like to check if this is the common translation in Latin American countries. I think that in Spain the common term is just "división entera".
Thanks.

**Comment by pambus** [comment]
In Chile I have only heard "función piso". I chose "división entera de tipo piso" since I thought it was less ambiguous... but I think "división entera" sounds way better, we should change it.

**Comment by oscarbelmon** [comment]
Ok, thanks Pamela. I shall use "división entera".
