### ISSUE TITLE
Clean up index (e.g Replace "see=" with "mire " or "ver " )

### ISSUE THREAD

**Issue by christianpeel** [JuliaIntro/IntroAJulia.jl#48]
The source asciidoc files contain text to create an index in the PDF version of the book. Some of the index entries point to another index entry using the text "see=".  I.e. the index entry for π says "see=pi". I think "see" is a holdover from the English book, so we'll replace it with "mire" or perhaps "ver".   This replacement will likely be done after we get our .travis.yml file configured to build a PDF in #46.

**Comment by longemen3000** [comment]
what about _véase_ ? is the most formal conjugation of _ver_ i found after looking at some books

**Comment by christianpeel** [comment]
I used *véase* in the updates to the index in #52.   I'd be happy for others to comment on this.
